<?php

namespace KMJ\ToolkitBundle\Tests\DependencyInjection;

use PHPUnit_Framework_TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-11-30 at 12:32:39.
 */
class ConfigurationTest extends PHPUnit_Framework_TestCase {

  

}
