<?php

namespace KMJ\ToolkitBundle\Tests\DataFixtures\Alice\Processor;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-11-28 at 17:01:42.
 */
class UserProcessorTest extends \PHPUnit_Framework_TestCase
{

    public function testPostProcess()
    {
        $processor = $this->getProcessor();
        $user = $this->getMockForAbstractClass("KMJ\ToolkitBundle\Entity\User");
        $this->assertTrue($processor->postProcess($user));
        $this->assertFalse($processor->postProcess((object) array("test" => "test")));
    }

    protected function getProcessor()
    {
        $fos = $this->getMockBuilder("FOS\UserBundle\Model\UserManager")
            ->disableOriginalConstructor()
            ->getMock();

        return new \KMJ\ToolkitBundle\DataFixtures\Alice\Processor\UserProcessor($fos);
    }
}
