<?php

namespace KMJ\ToolkitBundle\Entity;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-01-29 at 20:39:10.
 */
class BaseDocumentTest extends \PHPUnit_Framework_TestCase
{

    /**
     * 
     * @return BaseDocument
     */
    private function getBaseDocument()
    {
        $stub = $this->getMockForAbstractClass(BaseDocument::class);
        
        $stub->method("rootPath")
            ->willReturn("/tmp");
        
        $stub->method("getUploadDir")
            ->willReturn("/php-tests");

        return $stub;
    }

    /**
     * @covers KMJ\ToolkitBundle\Entity\BaseDocument::__toString
     */
    public function test__toString()
    {
        $bd = $this->getBaseDocument();
        $this->assertTrue($bd->__toString() === "unknown", "Document toString should be 'unknown'");
        $bd->setName("Test document");
        $this->assertTrue($bd->__toString() === "Test document", "Document toString is not returning the name");
    }

    /**
     * @covers KMJ\ToolkitBundle\Entity\BaseDocument::getPath
     */
    public function testGetPath()
    {
        //fake upload file
        $document = $this->getBaseDocument();

        $tmpFile = tmpfile();
        fwrite($tmpFile, "Temporary file");

        $tmpFileInfo = stream_get_meta_data($tmpFile);

        $uploadedFile = new \Symfony\Component\HttpFoundation\File\UploadedFile($tmpFileInfo['uri'], "tmpfile.txt", null, null, null, true);

        $document->setFile($uploadedFile);
        $document->preUpload();
        $document->uploadFile();
    }

    /**
     * @covers KMJ\ToolkitBundle\Entity\BaseDocument::getFile
     * @todo   Implement testGetFile().
     */
    public function testGetFile()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers KMJ\ToolkitBundle\Entity\BaseDocument::getName
     * @todo   Implement testGetName().
     */
    public function testGetName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers KMJ\ToolkitBundle\Entity\BaseDocument::getUploadedBy
     * @todo   Implement testGetUploadedBy().
     */
    public function testGetUploadedBy()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers KMJ\ToolkitBundle\Entity\BaseDocument::getUploadedDate
     * @todo   Implement testGetUploadedDate().
     */
    public function testGetUploadedDate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers KMJ\ToolkitBundle\Entity\BaseDocument::setPath
     * @todo   Implement testSetPath().
     */
    public function testSetPath()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers KMJ\ToolkitBundle\Entity\BaseDocument::setFile
     * @todo   Implement testSetFile().
     */
    public function testSetFile()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers KMJ\ToolkitBundle\Entity\BaseDocument::setName
     * @todo   Implement testSetName().
     */
    public function testSetName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers KMJ\ToolkitBundle\Entity\BaseDocument::setUploadedBy
     * @todo   Implement testSetUploadedBy().
     */
    public function testSetUploadedBy()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers KMJ\ToolkitBundle\Entity\BaseDocument::setUploadedDate
     * @todo   Implement testSetUploadedDate().
     */
    public function testSetUploadedDate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers KMJ\ToolkitBundle\Entity\BaseDocument::uploadPath
     * @todo   Implement testUploadPath().
     */
    public function testUploadPath()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers KMJ\ToolkitBundle\Entity\BaseDocument::getUploadRootDir
     * @todo   Implement testGetUploadRootDir().
     */
    public function testGetUploadRootDir()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers KMJ\ToolkitBundle\Entity\BaseDocument::getAbsolutePath
     * @todo   Implement testGetAbsolutePath().
     */
    public function testGetAbsolutePath()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers KMJ\ToolkitBundle\Entity\BaseDocument::getWebPath
     * @todo   Implement testGetWebPath().
     */
    public function testGetWebPath()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers KMJ\ToolkitBundle\Entity\BaseDocument::preUpload
     * @todo   Implement testPreUpload().
     */
    public function testPreUpload()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers KMJ\ToolkitBundle\Entity\BaseDocument::isImage
     * @todo   Implement testIsImage().
     */
    public function testIsImage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers KMJ\ToolkitBundle\Entity\BaseDocument::getMimeType
     * @todo   Implement testGetMimeType().
     */
    public function testGetMimeType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers KMJ\ToolkitBundle\Entity\BaseDocument::setMimeType
     * @todo   Implement testSetMimeType().
     */
    public function testSetMimeType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers KMJ\ToolkitBundle\Entity\BaseDocument::getChecksum
     * @todo   Implement testGetChecksum().
     */
    public function testGetChecksum()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers KMJ\ToolkitBundle\Entity\BaseDocument::setChecksum
     * @todo   Implement testSetChecksum().
     */
    public function testSetChecksum()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers KMJ\ToolkitBundle\Entity\BaseDocument::getExtension
     * @todo   Implement testGetExtension().
     */
    public function testGetExtension()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers KMJ\ToolkitBundle\Entity\BaseDocument::setExtension
     * @todo   Implement testSetExtension().
     */
    public function testSetExtension()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers KMJ\ToolkitBundle\Entity\BaseDocument::slug
     * @todo   Implement testSlug().
     */
    public function testSlug()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
