<?php
/**
 * This file is part of the KMJToolkitBundle
 * @copyright (c) 2014, Kaelin Jacobson
 */

namespace KMJ\ToolkitBundle\Entity;

use KMJ\ToolkitBundle\Entity\HiddenDocument;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-01-29 at 19:51:39.
 */
class HiddenDocumentTest extends \KMJ\ToolkitBundle\Tests\Service\ToolkitTest
{
    /**
     * @var \KMJ\ToolkitBundle\Service\ToolkitService
     */
    protected $tk;

    public function setUp()
    {
        $this->tk = $this->getToolkit();
    }

    /**
     * @covers KMJ\ToolkitBundle\Entity\HiddenDocument::rootPath
     */
    public function testRootPath()
    {
        $hiddenDoc = $this->getHiddenDocument();
        $this->assertTrue($hiddenDoc->rootPath() === $this->tk->getRootDir().'/Resources/protectedUploads/',
            "Hidden document root path incorrect");
    }

    /**
     * @covers KMJ\ToolkitBundle\Entity\HiddenDocument::getUploadDir
     */
    public function testGetUploadDir()
    {
        $hiddenDoc = $this->getHiddenDocument();
        $this->assertTrue($hiddenDoc->getUploadDir() === "documents",
            "Hidden document directory incorrect");
    }

    /**
     * Gets a new WebDocument
     * @return HiddenDocument
     */
    private function getHiddenDocument()
    {
        return new HiddenDocument();
    }
}