<?php
/**
 * This file is part of the KMJToolkitBundle.
 *
 * @copyright (c) 2014, Kaelin Jacobson
 */

namespace KMJ\ToolkitBundle\Entity;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-01-29 at 19:51:39.
 */
class WebDocumentTest extends \KMJ\ToolkitBundle\Tests\Service\ToolkitTest
{
    /**
     * @var \KMJ\ToolkitBundle\Service\ToolkitService
     */
    protected $toolkit;

    public function setUp()
    {
        $this->toolkit = $this->getToolkit();
    }

    /**
     * @covers \KMJ\ToolkitBundle\Entity\WebDocument::rootPath
     */
    public function testRootPath()
    {
        $webDoc = $this->getWebDocument();
        $this->assertTrue(
            $webDoc->rootPath() === $this->toolkit->getRootDir().'/../web/',
            'Web document root path incorrect'
        );
    }

    /**
     * @covers \KMJ\ToolkitBundle\Entity\WebDocument::getUploadDir
     */
    public function testGetUploadDir()
    {
        $webDoc = $this->getWebDocument();

        $this->assertTrue(
            $webDoc->getUploadDir() === 'uploads/documents',
            'Web document directory incorrect'
        );
    }

    /**
     * Gets a new WebDocument.
     *
     * @return \KMJ\ToolkitBundle\Entity\WebDocument
     */
    private function getWebDocument()
    {
        return new WebDocument();
    }
}
